n = input('Digite algo:')
print('Esse número é?', (type(n)))
print('É númerico?', (n.isnumeric()))
print('É alfabético?', (n.isalpha()))
print('É decimal?', (n.isdecimal()))
print('É minusculo?', (n.islower()))
print('É maiusculo?', (n.isupper()))
print('É um digito?', (n.isdigit()))
print('verificação concluída.')
