frase = str(input('Digite uma frase')).upper().strip()
print('Analisando sua frase...')
print('A letra A aparece {} vezes'.format(frase.count('A')))
print('A letra aparece pela primeira vez na posição {}'.format(frase.find('A')+1))
print('A letra aparece por ultimo na posição {}'.format(frase.rfind('A')+1))
